### ISSUE TITLE
screenshot_as_a_service missing yaml dependency

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#45]
Another issue with trying to run `bowl performance`.

```
13:57:02 stagecraft.1              | Cleaning up...
13:57:02 screenshot_as_a_service.1 | npm WARN package.json screenshot-as-a-service@1.1.1 No repository field.
13:57:02 screenshot_as_a_service.1 | npm WARN package.json config@0.4.15 No repository field.
13:57:03 screenshot_as_a_service.1 | npm WARN unmet dependency /var/apps/screenshot-as-a-service/node_modules/express/node_modules/connect requires qs@'0.6.6' but will load
13:57:03 screenshot_as_a_service.1 | npm WARN unmet dependency /var/apps/screenshot-as-a-service/node_modules/qs,
13:57:03 screenshot_as_a_service.1 | npm WARN unmet dependency which is version 0.6.5
13:57:03 screenshot_as_a_service.1 | 
13:57:03 screenshot_as_a_service.1 | /var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:728
13:57:03 screenshot_as_a_service.1 |     throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3)
13:57:03 screenshot_as_a_service.1 |           ^
13:57:03 screenshot_as_a_service.1 | Error: Cannot parse config file: '/var/apps/screenshot-as-a-service/config/default.yaml': Error: Cannot find module 'yaml'
13:57:03 screenshot_as_a_service.1 |     at Config._parseFile (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:728:11)
13:57:03 screenshot_as_a_service.1 |     at /var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:597:25
13:57:03 screenshot_as_a_service.1 |     at Array.forEach (native)
13:57:03 screenshot_as_a_service.1 |     at /var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:594:14
13:57:03 screenshot_as_a_service.1 |     at Array.forEach (native)
13:57:03 screenshot_as_a_service.1 |     at Config._loadFileConfigs (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:593:13)
13:57:03 screenshot_as_a_service.1 |     at new Config (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:99:5)
13:57:03 screenshot_as_a_service.1 |     at Object.<anonymous> (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:1081:64)
13:57:03 screenshot_as_a_service.1 |     at Module._compile (module.js:456:26)
13:57:03 screenshot_as_a_service.1 |     at Object.Module._extensions..js (module.js:474:10)
13:57:03 screenshot_as_a_service.1 | exited with code 8
```

**Comment by alexmuller** [comment]
From in the `screenshot_as_a_service` directory, can you try `rm -rf node_modules` and `npm install` again? It looks like dependency installation might be dodgy.

**Comment by pwaller** [comment]
Seemed to get further but then fell over because:

```
15:15:34 stagecraft.1              | Error: That port is already in use.
15:15:34 stagecraft.1              | exited with code 1
15:15:34 system                    | sending SIGTERM to all processes
15:15:34 spotlight.1               | 
15:15:34 spotlight.1               | module.js:340
15:15:34 screenshot_as_a_service.1 | terminated by SIGTERM
15:15:34 spotlight.1               | terminated by SIGTERM
15:15:34 backdrop_read.1           | terminated by SIGTERM
15:15:34 backdrop_write.1          | terminated by SIGTERM
15:15:34 backdrop_admin.1          | terminated by SIGTERM
15:15:34                           |     throw err;
15:15:34                           |           ^
15:15:34                           | Error: Cannot find module './lexer'
15:15:34                           |     at Function.Module._resolveFilename (module.js:338:15)
15:15:34                           |     at Function.Module._load (module.js:280:25)
15:15:34                           |     at Module.require (module.js:364:17)
15:15:34                           |     at require (module.js:380:17)
15:15:34                           |     at Object.<anonymous> (/var/apps/spotlight/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:10:10)
15:15:34                           |     at Object.<anonymous> (/var/apps/spotlight/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:167:4)
15:15:34                           |     at Module._compile (module.js:456:26)
15:15:34                           |     at Object.Module._extensions..js (module.js:474:10)
15:15:34                           |     at Module.load (module.js:356:32)
15:15:34                           |     at Function.Module._load (module.js:312:12)
```

I'm halting and re-upping the machine.

**Comment by pwaller** [comment]
Next:

```
15:17:13 screenshot_as_a_service.1 | started with pid 2895
15:17:13 spotlight.1               | started with pid 2897
15:17:13 backdrop_read.1           | started with pid 2899
15:17:13 backdrop_write.1          | started with pid 2903
15:17:13 backdrop_admin.1          | started with pid 2905
15:17:13 stagecraft.1              | started with pid 2909
15:17:13 screenshot_as_a_service.1 | Installing Node.js dependencies...
15:17:13 spotlight.1               | Installing Node.js and Ruby dependencies...
15:17:13 backdrop_write.1          | waiting for startup lock
15:17:13 backdrop_admin.1          | waiting for startup lock
15:17:13 backdrop_read.1           | The --no-site-packages flag is deprecated; it is now the default behavior.
15:17:13 backdrop_read.1           | New python executable in /home/vagrant/.virtualenvs/backdrop-read-3038/bin/python
15:17:16 screenshot_as_a_service.1 | exited with code 8
15:17:16 system                    | sending SIGTERM to all processes
15:17:16 spotlight.1               | terminated by SIGTERM
15:17:16 backdrop_read.1           | terminated by SIGTERM
15:17:16 backdrop_write.1          | terminated by SIGTERM
15:17:16 backdrop_admin.1          | terminated by SIGTERM
15:17:16 stagecraft.1              | terminated by SIGTERM
```

**Comment by pwaller** [comment]
Probably not worth tackling this one until #46 is sorted.

**Comment by pwaller** [comment]
This is actually just a part of #50.
