### ISSUE TITLE
spotlight fails to start "Error: Cannot find module './lexer'"

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#49]
Another in the long list of problems preventing me from getting started.

```
18:22:01 spotlight.1               | module.js:340
18:22:01 spotlight.1               |     throw err;
18:22:01 spotlight.1               |           ^
18:22:01 spotlight.1               | Error: Cannot find module './lexer'
18:22:01 spotlight.1               |     at Function.Module._resolveFilename (module.js:338:15)
18:22:01 spotlight.1               |     at Function.Module._load (module.js:280:25)
18:22:01 spotlight.1               |     at Module.require (module.js:364:17)
18:22:01 spotlight.1               |     at require (module.js:380:17)
18:22:01 spotlight.1               |     at Object.<anonymous> (/var/apps/spotlight/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:10:10)
18:22:01 spotlight.1               |     at Object.<anonymous> (/var/apps/spotlight/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/coffee-script.js:167:4)
18:22:01 spotlight.1               |     at Module._compile (module.js:456:26)
18:22:01 spotlight.1               |     at Object.Module._extensions..js (module.js:474:10)
18:22:01 spotlight.1               |     at Module.load (module.js:356:32)
18:22:01 spotlight.1               |     at Function.Module._load (module.js:312:12)
18:22:01 spotlight.1               | exited with code 8
```

**Comment by pwaller** [comment]
This is the current blocking issue.

**Comment by pwaller** [comment]
Cause: #50
