### ISSUE TITLE
screenshot-as-a-service missing module 'yaml'

### ISSUE THREAD

**Issue by pwaller** [alphagov/pp-development#58]
I'm reverting some of my local workarounds and I get this, currently:

```
10:15:09 screenshot_as_a_service.1 | /var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:728
10:15:09 screenshot_as_a_service.1 |     throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3)
10:15:09 screenshot_as_a_service.1 |           ^
10:15:09 screenshot_as_a_service.1 | Error: Cannot parse config file: '/var/apps/screenshot-as-a-service/config/default.yaml': Error: Cannot find module 'yaml'
10:15:09 screenshot_as_a_service.1 |     at Config._parseFile (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:728:11)
10:15:09 screenshot_as_a_service.1 |     at /var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:597:25
10:15:09 screenshot_as_a_service.1 |     at Array.forEach (native)
10:15:09 screenshot_as_a_service.1 |     at /var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:594:14
10:15:09 screenshot_as_a_service.1 |     at Array.forEach (native)
10:15:09 screenshot_as_a_service.1 |     at Config._loadFileConfigs (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:593:13)
10:15:09 screenshot_as_a_service.1 |     at new Config (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:99:5)
10:15:10 screenshot_as_a_service.1 |     at Object.<anonymous> (/var/apps/screenshot-as-a-service/node_modules/config/lib/config.js:1081:64)
10:15:10 screenshot_as_a_service.1 |     at Module._compile (module.js:456:26)
10:15:10 screenshot_as_a_service.1 |     at Object.Module._extensions..js (module.js:474:10)
10:15:10 screenshot_as_a_service.1 | exited with code 8
```

Should saas have a yaml dependency in its [`package.json`](https://github.com/alphagov/screenshot-as-a-service/blob/master/package.json)?

**Comment by alexmuller** [comment]
I'm unable to reproduce this by running the following commands:

``` bash
cd /var/apps/screenshot-as-a-service
# Clean up
$ rm -rf node_modules
$ npm cache clean # not totally sure this is necessary
# Install
$ npm install
# Run
$ node app.js
Phantomjs internal server listening on port 3001
Express server listening on port 3000
```

Does that do anything for you?

**Comment by pwaller** [comment]
Okay, that fixed it. Probably a knock on from #50. Thanks @alexmuller.
