### ISSUE TITLE
Provisioning error: virtualenvwrapper

### ISSUE THREAD

**Issue by alexmuller** [alphagov/pp-development#60]
Puppet output:

```
[bootstrap] Notice: /Stage[main]/Python::Install/Package[python-virtualenv]/ensure: ensure changed 'purged' to 'present'
[bootstrap] Notice: /Stage[main]/Python::Install/Package[python2.7-dev]/ensure: ensure changed 'purged' to 'present'
[bootstrap] Error: Execution of '/usr/bin/pip install -q virtualenvwrapper' returned 1: Command python setup.py egg_info failed with error code 1
[bootstrap] Storing complete log in /root/.pip/pip.log
[bootstrap] 
[bootstrap] Error: /Stage[main]/Main/Node[default]/Package[virtualenvwrapper]/ensure: change from absent to present failed: Execution of '/usr/bin/pip install -q virtualenvwrapper' returned 1: Command python setup.py egg_info failed with error code 1
[bootstrap] Storing complete log in /root/.pip/pip.log
```

pip.log:

```
  Using version 4.2 (newest of versions: 4.2, 4.1.1, 4.1, 4.0, 3.7.1, 3.7, 3.6.1, 3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3.0.1, 3.0, 2.11.1, 2.11, 2.10.1, 2.10, 2.9, 2.8, 2.7.1, 2.7, 2.6.3, 2.6.2, 2.6.1, 2.6, 2.5.3)
  Downloading from URL https://pypi.python.org/packages/source/v/virtualenvwrapper/virtualenvwrapper-4.2.tar.gz#md5=e13705ac2b136b02748e82947e3e2c8d (from https://pypi.python.org/simple/virtualenvwrapper/)
  Running setup.py egg_info for package virtualenvwrapper

    Installed /var/apps/pp-puppet/build/virtualenvwrapper/pbr-0.7.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/var/apps/pp-puppet/build/virtualenvwrapper/setup.py", line 7, in <module>
        pbr=True,
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (pip 1.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('pip>=1.4'))
```

Nice use of "XXX put more info here".

Looks like we have pip 1.0 on the box and virtualenvwrapper wants 1.4.

**Comment by IanHopkinson** [comment]
+1
I did:
`sudo apt-get install python-pip`
To update then installed virtualenvwrapper
